---
## Copy keys files and configuration

- name: transfer ssh config /etc/ssh/ssh_config
  template: src=keys/ssh_config dest=/etc/ssh/ssh_config owner=root
  tags:
    - ssh-config


- name: transfer global deployment Key ubuntu id_rsa_deploy_all
  template: src="./../../../ssh/keys/deploy_all" dest=/home/ubuntu/.ssh/deploy_all owner=ubuntu group=ubuntu mode=0600 force=yes
  tags:
    - keys-deploy
    - keys-ubuntu-deploy






