---
- name: nginx-server
  hosts: nginx-server
  remote_user: ubuntu
  become: yes
  roles:
    - { role: common,          tags: [ 'common'         ] }
    - { role: nginx,          tags: [ 'nginx'         ] }
